naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'

complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 14
    ignoreDefaultParameters: true
  TooManyFunctions:
    # disabled, since it does not make sense to count number of methods,
    # what is important is the readability and the total length of the file
    # `LargeClass` is supposed to help with this
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/endtoendtest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']