name: Auto deploy snapshot artifacts on draft release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Release tag
        run: |
          git describe --tags --always --first-parent
          git tag
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Generate cache key
        run: ./scripts/checksum.sh ./ checksum.txt

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
            build-cache
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Publish application
        run: |
          echo VERSION_NAME=2.0.0-SNAPSHOT > ./local.properties
          ./gradlew publishAllPublicationsToMavenCentralRepository --rerun-tasks --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2